export default [
  "Uma editora em 1631 publicou uma Bíblia com o seguinte erro de digitação: “Tu cometerás adultério”. Apenas nove dessas Bíblias, conhecidas como a “Bíblia dos Pecadores” existem hoje no mundo.",
  "A palavra “bíblia” vem do grego ta biblia, que significa “os rolos” ou “os livros”. A palavra é derivada da antiga cidade de Biblos, que era a fornecedora oficial de produtos de papel para o mundo antigo.",
  "A Bíblia completa foi traduzida para quinhentos e trinta e dois idiomas. Ele foi parcialmente traduzido para dois mil oitocentos e oitenta e três idiomas.",
  "A Bíblia não é uma única obra, mas uma coleção de obras de uma ampla variedade de autores, como pastores, reis, fazendeiros, sacerdotes, poetas, escribas e pescadores. Os autores também incluem traidores, estelionatários, adúlteros, assassinos e auditores.",
  "A Bíblia King James contém 788.258 palavras, 31.102 versículos, 1.189 capítulos e 66 livros.",
  "Embora seja o verso mais curto em inglês, não é o mais curto nas línguas originais. O versículo mais curto da Bíblia é João 11:35, que afirma: “Jesus chorou”.",
  "O capítulo mais longo da Bíblia é o Salmo 119.",
  "O menor livro da Bíblia é o Salmo 117, com apenas 2 versículos.",
  "O versículo mais longo da Bíblia é Ester 8:9",
  "Quase 8 em cada 10 americanos consideram a Bíblia como a palavra literal de Deus ou como inspirada por Deus.",
  "As mulheres são mais prováveis ​​do que os homens, as pessoas mais velhas são mais prováveis ​​do que os mais jovens e os afro-americanos têm mais probabilidade do que outras raças de ler a Bíblia.",
  "De acordo com um autor, Deus matou cerca de 25 milhões de pessoas na Bíblia. Satanás mata cerca de 60 pessoas, 10 das quais Deus permitiu que Satanás matasse como parte de uma aposta no Livro de Jó.",
  "A palavra mais longa na Bíblia é “Mahershalalhashbaz” (Isaías 8:3)",
  "Embora tenha demorado mais de 1.000 anos para escrever o Antigo Testamento, o Novo Testamento foi escrito dentro de um período de 50-75 anos.",
  "Não existem escritos originais da Bíblia.",
  "Mais de 100 milhões de cópias da Bíblia são vendidas a cada ano.",
  "A Bíblia informa a tradição das três principais religiões do mundo: Cristianismo , Judaísmo e Islã.",
  "Os três livros mais destacados de todos os tempos no Kindle são (1) A Bíblia Sagrada de Crossway Bibles, (2) Steve Jobs de Walter Isaacson e (3) Jogos Vorazes.",
  "John Wycliffe produziu a primeira tradução de toda a Bíblia da Vulgata latina para o inglês. No entanto, depois que ele morreu, a Igreja Católica exumou e queimou seu cadáver como punição por seu trabalho de tradução.",
  "William Tyndale produziu a primeira edição impressa do Novo Testamento em inglês. Mais tarde, ele foi queimado na fogueira por seus esforços.",
  "O nome de Adão vem da palavra hebraica a da ma , que significa “o solo”.",
  "A primeira Bíblia autorizada impressa em inglês é a Grande Bíblia de 1539. O rei Henrique VIII da Inglaterra declarou que ela deveria ser lida em voz alta durante os serviços religiosos na Igreja da Inglaterra.",
  "A China não é apenas o maior produtor de têxteis e produtos manufaturados do mundo; o país também é o maior produtor de Bíblias.",
  "A Bíblia de Genebra é a primeira Bíblia a usar versículos numerados. É também a Bíblia que Shakespeare usou e aquela que os Peregrinos trouxeram para a América em 1620.",
  "Embora não haja descrições de Jesus na Bíblia, a imagem dele com pele clara, cabelos claros e olhos azuis é provavelmente incorreta e reflete as influências culturais dos cristãos europeus. Cristo provavelmente tinha mais características do Oriente Médio.",
  "A Bíblia é o livro roubado mais comumente no mundo, provavelmente porque está disponível em quartos de hotel e locais de culto.",
  "Os muçulmanos acreditam que a Bíblia é uma revelação de Deus que foi corrompida pelos homens. Eles acreditam que o Alcorão é sua correção.",
  "A King James Bible (1611) é considerada incomparável em sua exatidão e beleza literária. Além de 54 estudiosos, Shakespeare provavelmente ajudou na tradução.",
  "A Bíblia de Robert Aitken (The King James Version without the Apocrypha) foi a primeira Bíblia em inglês impressa na América.",
  "A Bíblia ocorre em três continentes: Ásia, África e Europa.",
  "Acredita-se que o auge da arte renascentista seja “A Criação de Adão”, de Michelangelo, uma obra que retrata em uma única imagem toda a história bíblica do relacionamento de Deus com a humanidade.",
  "A Bíblia não menciona quantos magos homens visitou Cristo, só que eles trouxeram três tipos de presentes: ouro, incenso e mirra.",
  "Assim como muitos clássicos, Moby Dick de Herman Melville se baseia fortemente na alegoria bíblica. Especificamente, vários personagens têm nomes de figuras bíblicas, como Ismael e Acabe.",
  "A Bíblia é o livro mais vendido da história, com vendas totais superiores a 5 bilhões de cópias.",
  "Charlton Heston foi escalado como Moisés no filme de sucesso Os Dez Mandamentos, em parte porque ele se parecia com a famosa estátua de Moisés de Michelangelo. Heston mais tarde interpretaria Michelangelo no filme The Agony and the Ecstasy (1965).",
  "O blockbuster de 1999 The Matrix baseia-se fortemente na Bíblia. A base rebelde do filme é conhecida como Sião, o navio principal se chama Nabucodonosor (em homenagem ao rei bíblico) e o personagem de Judas do filme se chama Cypher em referência ao nome LuCIPHER.",
  "Jesus não foi filho único. Ele tinha pelo menos 4 irmãos mencionados pelo nome e pelo menos 2 irmãs não identificadas.",
  "A palavra “Cristo” vem do grego khristos , que significa “o ungido”, que é o substantivo do adjetivo verbal khriein, que significa “esfregar a unção”.",
  "Existem 93 mulheres que falam na Bíblia, 49 das quais são mencionadas. Elas falam um total de 14.056 palavras, ou cerca de 1,1% da Bíblia. Há um total de 188 mulheres nomeadas na Bíblia.",
  "O autor polonês Joseph Conrad aprendeu inglês lendo páginas da Bíblia antes de rasgá-las e enrolá-las em cigarros.",
  "Johannes Gutenberg não ganhou nenhum dinheiro com suas Bíblias. A Bíblia de Gutenberg foi o primeiro livro a ser impresso com tipos de metal móveis.",
  "O livro mais caro do mundo é a tradução dos salmos bíblicos, “The Bay Psalm Book”, que foi vendido por mais de $ 14 milhões. É o primeiro livro impresso na América e foi a tentativa do Puritano de fazer a tradução do livro do Antigo Testamento.",
  "A menor Bíblia do mundo cabe na ponta de uma caneta. Os cientistas gravaram 1,2 milhão de letras do Antigo Testamento em um minúsculo disco de silicone, que eles chamam de Nano Bíblia.",
  "A maior Bíblia do mundo pesa 1.094 libras. Construído por Louis Waynai em 1930, o livro tem 43.5 polegadas de altura e uma largura de 98 polegadas.",
  "A palavra “Lúcifer” vem do latim lux “luz” + ferre “carregar” ou, literalmente, “trazendo luz”.",
  "A última palavra da Bíblia é Amém.",
  "Quase todos os vilões da Bíblia têm cabelos ruivos.",
];
